repos:
  - repo: https://github.com/ministryofjustice/devsecops-hooks
    rev: v1.2.0
    hooks:
      - id: baseline
        name: Ministry of Justice - Security scan

  - repo: local
    hooks:
      - id: lint
        name: Lint check
        entry: npm run validate:all
        language: system
        pass_filenames: false

  - repo: local
    hooks:
      - id: spellcheck
        name: Spell check
        entry: npm run spellcheck
        language: system
        pass_filenames: false
